# This rule is not used by the project kaas itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kaas.faithbyte.kaas.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kaas
    app.kubernetes.io/managed-by: kustomize
  name: job-admin-role
rules:
- apiGroups:
  - kaas.faithbyte.kaas
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - kaas.faithbyte.kaas
  resources:
  - jobs/status
  verbs:
  - get
