# This rule is not used by the project kaas-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to faithbyte.kaas resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kaas-controller
    app.kubernetes.io/managed-by: kustomize
  name: jobsteps-viewer-role
rules:
- apiGroups:
  - faithbyte.kaas
  resources:
  - jobsteps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - faithbyte.kaas
  resources:
  - jobsteps/status
  verbs:
  - get
