apiVersion: faithbyte.kaas/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: kaas-controller
    app.kubernetes.io/managed-by: kustomize
  name: job-sample
spec:
  # TODO(user): Add fields here
